package domain

import "errors"

var (
	ErrInvalidTaxID               = errors.New("invalid tax id")
	ErrMissingDocumentType        = errors.New("document type is required")
	ErrInvalidDocumentType        = errors.New("invalid document type")
	ErrMissingCustomer            = errors.New("customer is required")
	ErrMissingSeries              = errors.New("series is required")
	ErrMissingDate                = errors.New("document date is required")
	ErrNoLines                    = errors.New("at least one line is required")
	ErrSeriesAlreadyRegistered    = errors.New("series already registered")
	ErrInvalidCountry             = errors.New("invalid country code")
	ErrMissingAddressDetail       = errors.New("address detail is required")
	ErrMissingCity                = errors.New("city is required")
	ErrMissingPostalCode          = errors.New("postal code is required")
	ErrMissingAccountID           = errors.New("account id is required")
	ErrMissingCompanyName         = errors.New("company name is required")
	ErrMissingProductCode         = errors.New("product code is required")
	ErrInvalidProductType         = errors.New("invalid product type")
	ErrMissingProductDescription  = errors.New("product description is required")
	ErrMissingProductNumberCode   = errors.New("product number code is required")
	ErrInvalidUnit                = errors.New("invalid unit of measure")
	ErrDateRegression             = errors.New("document date precedes previous issue in series")
	ErrSubCentPrecision           = errors.New("money value has sub-cent precision")
	ErrCancellationDeadlinePassed = errors.New("cancellation deadline has passed; use recovery flow")
	ErrNotRecoverySeries          = errors.New("recovery documents require a dedicated recovery series")
	ErrRecoverySeriesMisuse       = errors.New("recovery series cannot issue normal documents")
)
