package domain

import "errors"

var (
	ErrInvalidTaxID               = errors.New("invalid tax id")
	ErrMissingDocumentType        = errors.New("document type is required")
	ErrInvalidDocumentType        = errors.New("invalid document type")
	ErrMissingCustomer            = errors.New("customer is required")
	ErrMissingSeries              = errors.New("series is required")
	ErrMissingDate                = errors.New("document date is required")
	ErrNoLines                    = errors.New("at least one line is required")
	ErrSeriesAlreadyRegistered    = errors.New("series already registered")
	ErrInvalidCountry             = errors.New("invalid country code")
	ErrMissingAddressDetail       = errors.New("address detail is required")
	ErrMissingCity                = errors.New("city is required")
	ErrMissingPostalCode          = errors.New("postal code is required")
	ErrMissingCompanyName         = errors.New("company name is required")
	ErrMissingProductCode         = errors.New("product code is required")
	ErrInvalidProductType         = errors.New("invalid product type")
	ErrMissingProductDescription  = errors.New("product description is required")
	ErrMissingProductNumberCode   = errors.New("product number code is required")
	ErrInvalidUnit                = errors.New("invalid unit of measure")
	ErrDateRegression             = errors.New("document date precedes previous issue in series")
	ErrDateBeforeRegistration     = errors.New("document date precedes series AT registration")
	ErrMissingRegistrationDate    = errors.New("series is active but has no registration date")
	ErrSubCentPrecision           = errors.New("money value has sub-cent precision")
	ErrCancellationDeadlinePassed = errors.New("cancellation deadline has passed; use recovery flow")
	ErrNotRecoverySeries          = errors.New("recovery documents require a dedicated recovery series")
	ErrIntegratedNotSupported     = errors.New("SourceBilling \"I\" (integrated document) is not supported: integration must not recompute or re-sign the originating system's document")
	ErrHasLiveRectifyingNote      = errors.New("cannot annul a document that has a live rectifying note; annul the note first")
	ErrRecoverySeriesMisuse       = errors.New("recovery series cannot issue normal documents")
	ErrSeriesNotActive            = errors.New("series is not active")
	ErrSeriesHasDocuments         = errors.New("series with issued documents cannot be cancelled; finalize it instead")
	ErrSystemEntryRegression      = errors.New("system entry date precedes previous issue in series")
	ErrUnknownSourceDoc           = errors.New("allocation references a document unknown to the system")
	ErrSourceDocCancelled         = errors.New("allocation references a cancelled document")
	ErrSourceCustomerMismatch     = errors.New("allocation source document belongs to a different customer")
	ErrAllocationExceedsSource    = errors.New("cumulative allocations exceed source document total")
	ErrGlobalDiscountExceedsNet   = errors.New("global discount exceeds the document's post-line-discount net total")
	ErrGlobalDiscountOnZeroNet    = errors.New("global discount requires a positive post-line-discount net total")
)
